services:
  mongodb:
    image: mongo:latest
    container_name: mongobooks
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: